[custom]

# 基于blackmatrix7
# 基于hope140
# 自用
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.yaml
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml
ruleset=🍃 广告拦截,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml
ruleset=🍃 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hijacking/Hijacking.yaml
#ruleset=🍃 广告拦截,clash-domain:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite_Domain.yaml
ruleset=🍃 广告拦截,clash-classic:https://raw.githubusercontent.com/lztxi/ADH/main/op/bc.yaml
ruleset=🍃 广告拦截,clash-classic:https://raw.githubusercontent.com/lztxi/ADH/main/op/tcl.yaml
ruleset=Ⓜ️ 微软服务,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
ruleset=🍎 苹果服务,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml
ruleset=📲 电报消息,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
ruleset=🎮 游戏平台,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.yaml
ruleset=🎮 游戏平台,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml
ruleset=🎥 油管视频,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
#ruleset=🎥 油管视频,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
ruleset=💻 国内视频,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TencentVideo/TencentVideo.yaml
ruleset=💻 国内视频,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.yaml
ruleset=💻 国内视频,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouYin/DouYin.yaml
ruleset=💻 国内视频,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/KuaiShou/KuaiShou.yaml
ruleset=✈️ 节点选择,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Developer/Developer.yaml
ruleset=✈️ 节点选择,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ProxyLite/ProxyLite.yaml
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.yaml
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL


custom_proxy_group=✈️ 节点选择`select`[]♻️ 自动选择`[]🍍 负载均衡`[]🚀 手动切换`[]DIRECT`.*
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.msftconnecttest.com/connecttest.txt`300
custom_proxy_group=🍍 负载均衡`load-balance`.*`http://www.msftconnecttest.com/connecttest.txt`300
custom_proxy_group=📲 电报消息`select`[]✈️ 节点选择`[]🚀 手动切换`[]🍍 负载均衡`[]DIRECT`.*
custom_proxy_group=🎥 油管视频`select`[]✈️ 节点选择`[]🚀 手动切换`[]🍍 负载均衡`[]DIRECT`.*
custom_proxy_group=🎮 游戏平台`select`[]🎯 全球直连`[]🚀 手动切换`[]🍍 负载均衡
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 手动切换`[]🍍 负载均衡
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🚀 手动切换`[]🍍 负载均衡
custom_proxy_group=🍃 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=💻 国内视频`select`[]🎯 全球直连`[]🚀 手动切换`[]🍍 负载均衡
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]✈️ 节点选择`[]🍍 负载均衡`[]🎯 全球直连


enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml
